### ISSUE TITLE
[Client] Detail_Layout 및 기능 구현

### ISSUE THREAD

**Issue by ds-k** [daeseongkim05/GGBD#74]
### Issue 
* Detail_Layout 및 기능 구현

### To-do
- [x] 상세 게시물 레이아웃
- [x] html로 글 써지도록
- [x] 응원하기
- [x] 스크랩하기
- [x] 게시글 수정 및 삭제
- [x] 댓글 컴포넌트 추가
